config/routes.rb
Rails.application.routes.draw do
  resources :doctors, :patients, except: [:show]
  resources :appointments
  root to: 'doctors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :starts_at, :ends_at, presence: true
  validates_time :starts_at, :ends_at, between: '9:00am'...'6:00pm'
  
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates :name, :crm_number, :crm_uf, presence: true
  validates :crm_number, uniqueness: {scope: :crm_uf}
  has_many :appointments

  def destroy
    raise "Médico não pode ser excluído pois possui consultas agendadas" unless appointments.count == 0
    super
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :name, :birth_date, :cpf, presence: true
  validates :cpf, length: { is: 11, message: 'São 11 números, tente novamente' }, on: %i[create update]
  validates :cpf, uniqueness: true
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[edit update]
  before_action :set_doctors_options, :set_patients_options, only: %i[new create edit update]

  def index
    @appointments = Appointment.all
  end
  
  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    return redirect_to appointments_path, notice:'Consulta cadastrada com sucesso' if @appointment.save
    render :new
  end

  def edit
  end

  def update
    return redirect_to appointments_path, notice: 'Consulta atualizado com sucesso!' if @appointment.update(appointment_params)
    render :edit
  end

  private

  def set_doctors_options
    @doctors_options = Doctor.all.pluck(:name, :id)
  end

  def set_patients_options
    @patients_options = Patient.all.pluck(:name, :id)
  end

  def appointment_params
    params.require(:appointment).permit(:starts_at, :ends_at, :doctor_id, :patient_id)
  end

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[edit update destroy]
  
  def index
    @doctors = Doctor.all
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    return redirect_to doctors_path, notice:'Médico cadastrado com sucesso' if @doctor.save
    render :new
  end

  def edit
  end

  def update
    return redirect_to doctors_path, notice: 'Médico atualizado com sucesso!' if @doctor.update(doctor_params)
    render :edit
  end

  def destroy
    return redirect_to doctors_path, notice: 'Médico excluído com sucesso!' if @doctor.destroy
    render :index
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :crm_number, :crm_uf)
  end

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[edit update destroy]

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    return redirect_to patients_path, notice: 'Paciente cadastrado com sucesso' if @patient.save
    render :new
  end

  def edit
  end

  def update
    return redirect_to patients_path, notice: 'Paciente atualizado com sucesso!' if @patient.update(patient_params)
    render :edit
  end

  def destroy
    return redirect_to patients_path, notice: 'Paciente excluído com sucesso!' if @patient.destroy
    render :index
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :birth_date, :cpf)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<% if @appointment.errors.any? %>
  <ul>
    <% @appointment.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @appointment do |f| %>
  <div class="field">
    <%= f.label :starts_at %>
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %>
    <%= f.time_field :ends_at %>
  </div>
  <div class="field">  
    <%= f.label :doctor_id %>
    <%= f.select("doctor_id", @doctors_options, {include_blank: 'Selecione o Médico'}) %>
  </div>
  <div class="field">
    <%= f.label :patient_id %>
    <%= f.select("patient_id", @patients_options, {include_blank: 'Paciente ...'}) %>
  </div>
  <div class="actions">
    <%= f.submit btn_description %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<section id="feature" class="feature-section pt-150">
  <div class="container">
    <h1>Editar Consulta</h1>

    <%= render partial: 'form', locals: { appointment: @appointment, btn_description: 'Atualizar Consulta' } %>
  </div>
</section>

app/views/appointments/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>  
<% end %>
<h1>Listagem de Consultas</h1>
<% if @appointments.empty? %>
  <h2>Não existe nenhum consulta cadastrado</h2>
<% end %>
<table>
  <thead>
    <tr>
      <td>Horário Início</td>
       <td>Horário Fim</td>
        <td>Paciente</td>
        <td>Médico</td>
    </tr>
    <tbody>
      <% @appointments.each do |appointment|%>
        <tr>
          <td><%= appointment.starts_at.strftime('%I:%M:%S %p') %></td>
           <td><%= appointment.ends_at.strftime('%I:%M:%S %p') %></td>
           <td><%= appointment.patient.name %></td>
           <td><%= appointment.doctor.name %></td>
          <td><%= link_to "Editar", edit_appointment_path(appointment) %></td>
          <td><%= link_to "Excluir", appointment, method: :delete, data: { confirm: 'Deseja realmente excluir'} %></td>
        </tr>
      <% end %>
    </tbody>
  </thead>
</table>  

app/views/appointments/new.html.erb
<div class="form-devise">
  <h2>Nova Consulta</h2>
  <%= render partial: 'form', locals: { appointment: @appointment, btn_description: 'Criar Consulta'  } %>
</div>

app/views/doctors/_form.html.erb
<% if @doctor.errors.any? %>
  <ul>
    <% @doctor.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @doctor do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :crm_number %>
    <%= f.text_field :crm_number %>

    <%= f.label :crm_uf %>
    <%= f.text_field :crm_uf %>
  </div>
  <p><%= f.submit btn_description %></p>
<% end %>

app/views/doctors/edit.html.erb
<section id="feature" class="feature-section pt-150">
  <div class="container">
    <h1>Editar Médico</h1>

    <%= render partial: 'form', locals: { doctor: @doctor, btn_description: 'Atualizar Médico' } %>
  </div>
</section>

app/views/doctors/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>  
<% end %>
<h1>Listagem de Médicos</h1>
<% if @doctors.empty? %>
  <h2>Não existe nenhum médico cadastrado</h2>
<% end %>
<table>
  <thead>
    <tr>
      <td>Nome do Médico</td>
       <td>CRM</td>
        <td>UF</td>
    </tr>
    <tbody>
      <% @doctors.each do |doctor|%>
        <tr>
          <td><%= doctor.name %></td>
           <td><%= doctor.crm_number %></td>
           <td><%= doctor.crm_uf %></td>
          <td><%= link_to "Editar", edit_doctor_path(doctor) %></td>
          <td><%= link_to "Excluir", doctor, method: :delete, data: { confirm: 'Deseja realmente excluir'} %></td>
        </tr>
      <% end %>
    </tbody>
  </thead>
</table>  

app/views/doctors/new.html.erb
<div class="form-devise">
  <h2>Novo Médico</h2>
  <%= render partial: 'form', locals: { doctor: @doctor, btn_description: 'Adicionar Médico'  } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalConsultation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<% if @patient.errors.any? %>
  <ul>
    <% @patient.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @patient do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :birth_date %>
    <%= f.text_field :birth_date %>

    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>
  <p><%= f.submit btn_description %></p>
<% end %>

app/views/patients/edit.html.erb
<section id="feature" class="feature-section pt-150">
  <div class="container">
    <h1>Editar Paciente</h1>

    <%= render partial: 'form', locals: { patient: @patient, btn_description: 'Atualizar Paciente' } %>
  </div>
</section>

app/views/patients/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>  
<% end %>
<h1>Listagem de Pacientes</h1>
<% if @patients.empty? %>
  <h2>Não existe nenhum paciente cadastrado</h2>
<% end %>
<table>
  <thead>
    <tr>
      <td>Nome do Paciente</td>
       <td>Data de Nascimento </td>
        <td>CPF</td>
    </tr>
    <tbody>
      <% @patients.each do |patient|%>
        <tr>
          <td><%= patient.name %></td>
           <td><%= patient.birth_date %></td>
           <td><%= patient.cpf %></td>
          <td><%= link_to "Editar", edit_patient_path(patient) %></td>
          <td><%= link_to "Excluir", patient, method: :delete, data: { confirm: 'Deseja realmente excluir'} %></td>
        </tr>
      <% end %>
    </tbody>
  </thead>
</table>  

app/views/patients/new.html.erb
<div class="form-devise">
  <h2>Novo Paciente</h2>
  <%= render partial: 'form', locals: { patient: @patient, btn_description: 'Adicionar Paciente'  } %>
</div>